autoload :FirstRoom, 'lib/first_room'
autoload :FeedingRoom, 'lib/feeding_room'
autoload :WashingRoom, 'lib/washing_room'
autoload :TrainingRoom, 'lib/training_room'
autoload :StylingRoom, 'lib/styling_room'
autoload :GuestRoom, 'lib/guest_room'
autoload :SleepingRoom, 'lib/sleeping_room'
autoload :HappyEnd, 'lib/happy_end'
autoload :MarkupHelper , 'lib/markup_helper'
autoload :Assets , 'lib/assets'
autoload :Death , 'lib/death'
autoload :DeathHelper , 'lib/death_helper'